from __future__ import annotations

import streamlit as st

from src.analytics import (
    available_months,
    available_quarters,
    available_years,
    filter_reviews_by_month,
    filter_reviews_by_quarter,
    filter_reviews_by_year,
    more_natural_expressions_to_dataframe,
    summarize_month,
    summarize_quarter,
    summarize_year,
    weak_points_to_dataframe,
)
from src.data_loader import load_or_fetch_reviews
from src.llm_summary import generate_period_summary


st.set_page_config(page_title="English Review Analytics", layout="wide")


@st.cache_data(show_spinner=False)
def cached_load_reviews(refresh: bool):
    return load_or_fetch_reviews(refresh=refresh)


@st.cache_data(show_spinner=False)
def cached_period_summary(summary, reviews, period_type: str):
    return generate_period_summary(summary, reviews, period_type)


def main() -> None:
    st.title("English Review Analytics")

    with st.sidebar:
        st.header("Data")
        st.caption("通常表示はローカル保存済みデータのみを使います。")
        sync = st.button("Sync from Notion", type="primary")
        if sync:
            cached_load_reviews.clear()
            st.session_state["cache_cleared"] = True

    with st.spinner("Syncing active month from Notion..." if sync else "Loading local reviews..."):
        load_result = load_or_fetch_reviews(refresh=True) if sync else cached_load_reviews(False)

    reviews = load_result.reviews
    debug = load_result.debug
    resolve_cache_event(debug.loaded_at, sync)

    for message in debug.messages:
        st.sidebar.caption(message)
    if debug.sync_requested:
        render_sync_result(debug)

    if any(item.status == "エラー" for item in debug.page_statuses):
        st.warning("一部または全てのNotionページを取得できませんでした。表示中のデータはローカルキャッシュを含む可能性があります。")

    if not reviews:
        if any(item.status == "エラー" for item in debug.page_statuses):
            st.error("Notionデータを読み込めませんでした。サイドバーのメッセージとNotion API設定を確認してください。")
        else:
            st.warning("ローカル保存済みレビューがありません。必要に応じて Sync from Notion を実行してください。")
        return

    period_type = st.segmented_control(
        "Aggregation",
        ["Monthly", "Quarterly", "Yearly"],
        default="Monthly",
    )
    selected_period, period_reviews, summary = select_period(reviews, period_type)
    if selected_period is None:
        st.warning("選択できる期間がありません。")
        return

    with st.spinner("Generating summary..."):
        period_summary = cached_period_summary(summary, period_reviews, period_type)
    summary.llm_summary = period_summary.text

    render_metrics(summary)

    render_period_summary(period_type, summary, period_summary)

    render_improvement_focus(period_reviews)


def select_period(reviews: list, period_type: str):
    if period_type == "Monthly":
        periods = available_months(reviews)
        selected = st.selectbox("Month", periods, index=0)
        return selected, filter_reviews_by_month(reviews, selected), summarize_month(reviews, selected)

    if period_type == "Quarterly":
        periods = available_quarters(reviews)
        selected = st.selectbox("Quarter", periods, index=0)
        return selected, filter_reviews_by_quarter(reviews, selected), summarize_quarter(reviews, selected)

    periods = available_years(reviews)
    selected = st.selectbox("Year", periods, index=0)
    return selected, filter_reviews_by_year(reviews, selected), summarize_year(reviews, selected)


def render_sync_result(debug) -> None:
    st.info("Sync from Notion completed. 通常表示はローカル保存済みデータを使います。")
    rows = [
        {
            "month": item.synced_month,
            "page_title": item.title,
            "status": item.status,
            "added": item.added_count,
            "updated": item.updated_count,
            "skipped": item.skipped_count,
            "error": item.error,
        }
        for item in debug.page_statuses
    ]
    if rows:
        st.dataframe(rows, width="stretch", hide_index=True)


def render_period_summary(period_type: str, summary, period_summary) -> None:
    st.subheader(f"{period_type} Summary")
    if period_summary.source == "llm":
        st.caption(f"Generated by OpenAI API ({period_summary.model})")
    else:
        st.caption("Generated by rule-based fallback")
    if period_summary.warning:
        st.warning(period_summary.warning)
    st.write(summary.llm_summary)


def render_improvement_focus(reviews: list) -> None:
    st.subheader("Improvement Focus")

    st.markdown("#### Weak Points")
    weak_points_df = weak_points_to_dataframe(reviews)
    if weak_points_df.empty:
        st.caption("この期間には weak points の記録はまだありません。")
    else:
        st.dataframe(weak_points_df, width="stretch", hide_index=True)

    st.markdown("#### More Natural Expressions")
    more_natural_df = more_natural_expressions_to_dataframe(reviews)
    if more_natural_df.empty:
        st.caption("この期間には more natural expressions の記録はまだありません。")
    else:
        st.dataframe(more_natural_df, width="stretch", hide_index=True)

def resolve_cache_event(loaded_at: str, refresh: bool) -> str:
    signature = str(refresh)
    previous = st.session_state.get("last_load")
    cache_cleared = st.session_state.pop("cache_cleared", False)

    if cache_cleared:
        event = "cache clear + fresh fetch"
    elif previous and previous.get("signature") == signature and previous.get("loaded_at") == loaded_at:
        event = "cache hit"
    else:
        event = "fresh fetch"

    st.session_state["last_load"] = {"signature": signature, "loaded_at": loaded_at}
    return event


def render_metrics(summary) -> None:
    cols = st.columns(6)
    cols[0].metric("Total Study Time", f"{summary.total_duration_minutes} min")
    cols[1].metric("Study Days", summary.study_days)
    cols[2].metric("Longest Streak", f"{summary.longest_streak} days")
    cols[3].metric("Reviews", summary.review_count)
    cols[4].metric("Phrases", summary.phrase_count)
    cols[5].metric("Reused Phrases", summary.reused_phrase_count)


if __name__ == "__main__":
    main()
