from __future__ import annotations

import streamlit as st

from src.analytics import (
    available_months,
    available_quarters,
    available_years,
    dedupe_phrases_to_dataframe,
    duration_by_day,
    filter_reviews_by_month,
    filter_reviews_by_quarter,
    filter_reviews_by_year,
    phrase_cards_for_reviews,
    phrases_to_dataframe,
    reviews_to_dataframe,
    summarize_month,
    summarize_quarter,
    summarize_year,
)
from src.data_loader import load_or_fetch_reviews
from src.llm_summary import generate_period_summary
from src.reuse_detector import summarize_reused_phrases


st.set_page_config(page_title="English Review Analytics", layout="wide")


@st.cache_data(show_spinner=False)
def cached_load_reviews(refresh: bool):
    return load_or_fetch_reviews(refresh=refresh)


@st.cache_data(show_spinner=False)
def cached_period_summary(summary, reviews, period_type: str):
    return generate_period_summary(summary, reviews, period_type)


def main() -> None:
    st.title("English Review Analytics")

    with st.sidebar:
        st.header("Data")
        refresh = st.button("Refresh from Notion", type="primary")
        if refresh:
            cached_load_reviews.clear()
            st.session_state["cache_cleared"] = True

    with st.spinner("Loading reviews..."):
        load_result = cached_load_reviews(refresh)

    reviews = load_result.reviews
    debug = load_result.debug
    cache_event = resolve_cache_event(debug.loaded_at, refresh)

    for message in debug.messages:
        st.sidebar.caption(message)

    if any(item.status == "エラー" for item in debug.page_statuses):
        st.warning("一部または全てのNotionページを取得できませんでした。表示中のデータはローカルキャッシュを含む可能性があります。")

    if not reviews:
        if any(item.status == "エラー" for item in debug.page_statuses):
            st.error("Notionデータを読み込めませんでした。サイドバーのメッセージとNotion API設定を確認してください。")
        else:
            st.warning("Notionからレビューが取得できませんでした。Notionページ本文と取得設定を確認してください。")
        return

    period_type = st.segmented_control(
        "Aggregation",
        ["Monthly", "Quarterly", "Yearly"],
        default="Monthly",
    )
    selected_period, period_reviews, summary = select_period(reviews, period_type)
    if selected_period is None:
        st.warning("選択できる期間がありません。")
        return

    with st.spinner("Generating summary..."):
        period_summary = cached_period_summary(summary, period_reviews, period_type)
    summary.llm_summary = period_summary.text

    render_metrics(summary)

    daily_duration = duration_by_day(period_reviews)
    if not daily_duration.empty:
        st.subheader("Study Time")
        st.bar_chart(daily_duration, x="date", y="duration_minutes")

    render_period_summary(period_type, summary, period_summary)

    render_reused_phrase_candidates(period_reviews)

    render_phrase_cards(period_reviews)

    st.subheader("Reviews")
    review_df = reviews_to_dataframe(period_reviews)
    st.dataframe(review_df, width="stretch", hide_index=True)


def select_period(reviews: list, period_type: str):
    if period_type == "Monthly":
        periods = available_months(reviews)
        selected = st.selectbox("Month", periods, index=0)
        return selected, filter_reviews_by_month(reviews, selected), summarize_month(reviews, selected)

    if period_type == "Quarterly":
        periods = available_quarters(reviews)
        selected = st.selectbox("Quarter", periods, index=0)
        return selected, filter_reviews_by_quarter(reviews, selected), summarize_quarter(reviews, selected)

    periods = available_years(reviews)
    selected = st.selectbox("Year", periods, index=0)
    return selected, filter_reviews_by_year(reviews, selected), summarize_year(reviews, selected)


def render_period_summary(period_type: str, summary, period_summary) -> None:
    st.subheader(f"{period_type} Summary")
    if period_summary.source == "llm":
        st.caption(f"Generated by OpenAI API ({period_summary.model})")
    else:
        st.caption("Generated by rule-based fallback")
    if period_summary.warning:
        st.warning(period_summary.warning)
    st.write(summary.llm_summary)


def render_reused_phrase_candidates(reviews: list) -> None:
    st.subheader("Reused Phrase Candidates")
    reused_summary = summarize_reused_phrases(reviews)
    if not reused_summary:
        st.caption("この期間の再利用候補はまだありません。")
        return

    st.dataframe(
        [
            {
                "phrase": item.phrase,
                "first_seen_date": item.first_seen_date,
                "reused_dates": ", ".join(item.reused_dates),
                "reuse_count": item.reuse_count,
                "matched_fields": ", ".join(item.matched_fields),
                "last_used_date": item.last_used_date,
                "retention_label": item.retention_label,
            }
            for item in reused_summary
        ],
        width="stretch",
        hide_index=True,
    )

def render_phrase_cards(reviews: list) -> None:
    st.subheader("Phrase Cards")
    phrase_cards = phrase_cards_for_reviews(reviews)
    priorities = available_priorities(phrase_cards)
    selected_priorities = st.multiselect(
        "Priority",
        options=priorities,
        default=default_priorities(priorities),
    )
    filtered_phrase_cards = filter_phrase_cards_by_priority(phrase_cards, selected_priorities)

    view_mode = st.radio(
        "Phrase card view",
        ["Dedupe Phrase Cards", "Raw Phrase Cards"],
        horizontal=True,
    )
    if view_mode == "Dedupe Phrase Cards":
        phrase_df = dedupe_phrases_to_dataframe(filtered_phrase_cards)
    else:
        phrase_df = phrases_to_dataframe(filtered_phrase_cards).drop(columns=["next_review_date"], errors="ignore")

    if phrase_df.empty:
        if phrase_cards:
            st.caption("選択したpriorityに一致するフレーズカードはありません。")
        else:
            st.caption("この期間のフレーズカードはありません。")
    else:
        st.dataframe(phrase_df, width="stretch", hide_index=True)


def resolve_cache_event(loaded_at: str, refresh: bool) -> str:
    signature = str(refresh)
    previous = st.session_state.get("last_load")
    cache_cleared = st.session_state.pop("cache_cleared", False)

    if cache_cleared:
        event = "cache clear + fresh fetch"
    elif previous and previous.get("signature") == signature and previous.get("loaded_at") == loaded_at:
        event = "cache hit"
    else:
        event = "fresh fetch"

    st.session_state["last_load"] = {"signature": signature, "loaded_at": loaded_at}
    return event


def available_priorities(cards: list) -> list[str]:
    priority_order = ["High", "Medium", "Low"]
    existing = {card.priority.strip() for card in cards if card.priority.strip()}
    ordered = [priority for priority in priority_order if priority in existing]
    extra = sorted(existing - set(priority_order))
    return ordered + extra


def default_priorities(priorities: list[str]) -> list[str]:
    defaults = [priority for priority in ["High", "Medium"] if priority in priorities]
    return defaults or priorities


def filter_phrase_cards_by_priority(cards: list, priorities: list[str]) -> list:
    selected = set(priorities)
    return [card for card in cards if card.priority in selected]


def render_metrics(summary) -> None:
    cols = st.columns(6)
    cols[0].metric("Total Study Time", f"{summary.total_duration_minutes} min")
    cols[1].metric("Study Days", summary.study_days)
    cols[2].metric("Longest Streak", f"{summary.longest_streak} days")
    cols[3].metric("Reviews", summary.review_count)
    cols[4].metric("Phrases", summary.phrase_count)
    cols[5].metric("Reused Phrases", summary.reused_phrase_count)


if __name__ == "__main__":
    main()
